language: c

sudo: false

services:
  - postgresql
  - mysql

addons:
  apt:
    packages:
      - libgmp-dev
      - postgresql-client
      - postgresql-server-dev-all

  postgresql: "9.6"

env:
 - GHCVER=8.2

install:
  - export STACK_YAML=stack-$GHCVER.yaml
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - stack --version
  - echo "CREATE USER esqutest WITH PASSWORD 'esqutest';" | psql postgres
  - createdb -O esqutest esqutest
  - echo "create user esqutest;" | mysql
  - echo "create database esqutest;" | mysql
  - echo "grant all on esqutest.* to 'esqutest'@'localhost' identified by 'esqutest';" | mysql

script:
  - stack setup
  - stack update
  - stack build
  - stack test -- esqueleto:postgresql
  - stack test -- esqueleto:sqlite
  - make test-mysql
  - ./should-not-typecheck.sh

cache:
  timeout: 2000
  directories:
  - $HOME/.cabal
  - $HOME/.ghc
  - $HOME/.stack
  - .stack-work/
  - /tmp
  apt: true
